targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - non_constant_identifier_names
            - type_annotate_public_apis
            - omit_local_variable_types
            - unnecessary_this

      freezed|freezed:
        enabled: true

      json_serializable:
        options:
          any_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
builders:
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: ["freezed"]
    build_extensions: { ".dart": [".freezed.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - json_serializable|json_serializable
      - source_gen|combining_builder