include: package:effective_dart/analysis_options.1.2.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/*"
    - "lib/src/model/*.g.dart"
    - "lib/src/model/*.freezed.dart"

linter:
  rules:
    nont_constatnt_identifier_names: false
    public_member_api_docs: false
    prefer_relative_imports: false
    prefer_single_quotes: true
    prefer_void_to_null: true
    avoid_equals_and_hash_code_on_mutable_classes: false