name: bullet_train
description: >-
  Flutter Client SDK for http://bullet-train.io, Bullet Train is 100% Open
  Source. Host yourself or let us take care of the hosting.
version: 0.0.4+3
homepage: https://github.com/printeastwoodcz/bullet_train_flutter
repository: https://github.com/printeastwoodcz/bullet_train_flutter
issue_tracker: https://github.com/printeastwoodcz/bullet_train_flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  sembast: ^2.4.7+6
  collection: ^1.14.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
