name: Analyze and Test
on: [push, pull_request]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    # todo: reenable this
    # - run: flutter analyze
    - run: flutter test
