# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
            - main
            - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    publishing:
        runs-on: ubuntu-latest
        name: Dart Publish Package

        steps:
            - name: 'Checkout'
              uses: actions/checkout@v2 # required!

            - name: '>> Dart package <<'
              uses: k-paxian/dart-package-publisher@master
              with:
                  accessToken: ${{ secrets.PUBDEV_ACCESSTOKEN }}
                  refreshToken: ${{ secrets.PUBDEV_REFRESHTOKEN }}