name: Analyze, test and publish
on:
  push:
    tags:
      - "*"

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Dart Analyze
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: 'any'
      - run: flutter pub get
      - run: flutter analyze

  # TODO enable this after upgrading to dart 3.x
  # score:
  #   runs-on: ubuntu-latest
  #   name: Dart package score

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: axel-op/dart-package-analyzer@v3
  #       with:
  #         githubToken: ${{ secrets.GITHUB_TOKEN }}

  publishing:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    name: Dart Publish Package
    needs: analyze
    steps:
      - uses: actions/checkout@v1
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1649072931936
          }
          EOF
      - name: Publish package
        run: pub publish -f
